#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  scripts/codex-worktree-setup.sh [idea-name] [port]

Creates a Codex-friendly Isoprism worktree for parallel local work.

When Codex Desktop provides CODEX_SOURCE_TREE_PATH and CODEX_WORKTREE_PATH,
the script configures that existing worktree instead of creating another one.

Environment overrides:
  CODEX_SOURCE_TREE_PATH  Source workspace path provided by Codex Desktop.
  CODEX_WORKTREE_PATH     New worktree path provided by Codex Desktop.
  CODEX_WORKTREE_PARENT   Parent directory for worktrees.
                         Default: $HOME/.codex/worktrees
  CODEX_WORKTREE_SLUG     Directory slug under CODEX_WORKTREE_PARENT.
                         Default: derived from CODEX_THREAD_ID and idea name
  CODEX_WORKTREE_BRANCH   Branch name for the new worktree.
                         Default: idea/<idea-name>
  CODEX_WEB_PORT          Next.js dev server port.
                         Default: second argument, then 3001
  CODEX_API_URL           Hosted API URL for frontend dev.
                         Default: https://api.isoprism.com

Example:
  scripts/codex-worktree-setup.sh
  CODEX_WEB_PORT=3002 scripts/codex-worktree-setup.sh graph-context
USAGE
}

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
  usage
  exit 0
fi

codex_managed=0
if [ -n "${CODEX_WORKTREE_PATH:-}" ]; then
  codex_managed=1
fi

if [ "$#" -lt 1 ] && [ "$codex_managed" != "1" ]; then
  usage
  exit 1
fi

idea_name="${1:-${CODEX_WORKTREE_IDEA:-$(basename "${CODEX_WORKTREE_PATH:-isoprism-worktree}")}}"
port="${CODEX_WEB_PORT:-${2:-3001}}"
api_url="${CODEX_API_URL:-https://api.isoprism.com}"

source_root="${CODEX_SOURCE_TREE_PATH:-$(git rev-parse --show-toplevel)}"
repo_name="$(basename "$source_root")"

safe_name="$(
  printf '%s' "$idea_name" |
    tr '[:upper:]' '[:lower:]' |
    tr -cs 'a-z0-9._-' '-'
)"
safe_name="${safe_name%-}"
safe_name="${safe_name#-}"

if [ -z "$safe_name" ]; then
  echo "Could not derive a safe name from: $idea_name" >&2
  exit 1
fi

thread_slug=""
if [ -n "${CODEX_THREAD_ID:-}" ]; then
  thread_slug="${CODEX_THREAD_ID%%-*}"
fi

default_slug="$safe_name"
if [ -n "$thread_slug" ]; then
  default_slug="$thread_slug-$safe_name"
fi

worktree_slug="${CODEX_WORKTREE_SLUG:-$default_slug}"
worktree_parent="${CODEX_WORKTREE_PARENT:-$HOME/.codex/worktrees}"
branch="${CODEX_WORKTREE_BRANCH:-idea/$safe_name}"
worktree_path="${CODEX_WORKTREE_PATH:-$worktree_parent/$worktree_slug/$repo_name}"

cd "$source_root"

if [ "$codex_managed" = "0" ] && [ -n "$(git status --porcelain)" ]; then
  echo "Refusing to create from a dirty source worktree:" >&2
  git status --short >&2
  echo >&2
  echo "Commit, stash, or rerun from a clean checkout of main." >&2
  exit 1
fi

if [ "$codex_managed" = "0" ]; then
  git checkout main
  git pull --ff-only origin main

  if git show-ref --verify --quiet "refs/heads/$branch"; then
    echo "Branch already exists: $branch" >&2
    exit 1
  fi

  mkdir -p "$(dirname "$worktree_path")"
  git worktree add "$worktree_path" -b "$branch" main
elif [ ! -d "$worktree_path" ]; then
  echo "CODEX_WORKTREE_PATH does not exist: $worktree_path" >&2
  exit 1
else
  current_branch="$(git -C "$worktree_path" branch --show-current 2>/dev/null || true)"
  if [ -z "${CODEX_WORKTREE_BRANCH:-}" ] && [ -n "$current_branch" ]; then
    branch="$current_branch"
  fi
fi

if [ -f "$source_root/api/.env" ]; then
  cp "$source_root/api/.env" "$worktree_path/api/.env"
fi

if [ -f "$source_root/web/.env.local" ]; then
  cp "$source_root/web/.env.local" "$worktree_path/web/.env.local"
fi

cat > "$worktree_path/.worktree.env" <<EOF
# Generated by scripts/codex-worktree-setup.sh
export NEXT_PUBLIC_API_URL=$api_url
export PORT=$port
export CODEX_WORKTREE_IDEA=$safe_name
export CODEX_WORKTREE_BRANCH=$branch
export CODEX_WORKTREE_PATH=$worktree_path
export CODEX_SOURCE_TREE_PATH=$source_root
EOF

(
  cd "$worktree_path/web"
  npm install
)

cat <<EOF

Codex worktree ready:

  Path:   $worktree_path
  Branch: $branch
  Env:    $worktree_path/.worktree.env

Run the web app:

  cd "$worktree_path/web"
  NEXT_PUBLIC_API_URL=$api_url npm run dev -- -p $port

Merge when verified:

  cd "$source_root"
  git checkout main
  git pull --ff-only origin main
  git merge $branch
  git push origin main

Clean up after merge:

  scripts/codex-worktree-cleanup.sh $safe_name

EOF
